### ISSUE TITLE
[FEATURE] Add background job to run on a schedule for Pivotal Tracker stories 

### ISSUE THREAD

**Issue by etagwerker** [fastruby/dash#39]
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (for multi-repository projects)

**Branch/Commit:**

Happening on `main` branch.

**Expected behavior:**

As a user I would like to see my Pivotal Tracker stories automatically synced every 10 minutes (without having to click the sync for Pivotal Tracker stories) 

**Actual behavior:**

As a user I see that my Pivotal Tracker stories are constantly out of sync with the right status in PT. Then I need to click the sync button for it to sync. 

**Steps to reproduce:**

1. Sync your Pivotal Tracker stories by clicking the Sync button for PT 
2. Go to PT and change said story's status
3. Wait for 20 minutes 
4. Refresh your TODO list page in Dash

You will see that changes are not reflected in Dash. 😢 

**Context and environment:**

Not relevant. All environments. 

**Screenshots and Videos**

Today I worked on this story: 

![Screen Shot 2020-09-25 at 12 25 07 AM](https://user-images.githubusercontent.com/17584/94226813-8cf3f780-fec6-11ea-8693-05f2fe83c580.png)

When I was done with it I moved it to Accept/Reject status: 

![Screen Shot 2020-09-25 at 12 25 27 AM](https://user-images.githubusercontent.com/17584/94226843-a137f480-fec6-11ea-855d-254a9cec64d2.png)

I waited for a couple of hours and I didn't see the status change in Dash. Only after clicking the Pivotal Tracker sync button I saw that its status changed: 

![Screen Shot 2020-09-25 at 12 26 10 AM](https://user-images.githubusercontent.com/17584/94226867-b3199780-fec6-11ea-961d-8ec4a043a163.png)

I see that we are using Heroku scheduler in production: 

![Screen Shot 2020-09-25 at 12 27 59 AM](https://user-images.githubusercontent.com/17584/94226899-c4fb3a80-fec6-11ea-854d-caa717603e45.png)

But it seems that we are only syncing issues and pull requests on a schedule: 

![Screen Shot 2020-09-25 at 12 28 30 AM](https://user-images.githubusercontent.com/17584/94226917-cfb5cf80-fec6-11ea-88cc-c9d84b9f3356.png)

**Potential Solution**

- [ ] If we don't have a rake task for Pivotal Tracker sync, then we should add one 
- [ ] We should schedule a rake task to sync PT stories every 10 minutes

**I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md)**

**Comment by cleicar** [comment]
This is duplicated with issue #3
